feat: UI improvements
openedx/frontend-app-learner-record pull request #319
Opened 2024-04-03 22:28 UTC by Lunyachek

This is backport from master - https://github.com/openedx/frontend-app-learner-record/pull/318

**Minor fix for Back to My Records button**

**First proposal:** make the button look the same as the button on the records page

**Second proposal:** remove the `<a>` tag from the `<button>` tag. The current approach is not recommended due to potential accessibility and semantic issues

<img width="1840" alt="Снимок экрана 2024-04-04 в 00 59 00" src="https://github.com/openedx/frontend-app-learner-record/assets/19806032/40f72d5d-b94a-4d17-a30f-48b46ee906c9">

- Decrease font size for the `Questions about Learner Records` title - to match with the same title on Records page

<img width="1840" alt="Снимок экрана 2024-04-04 в 01 10 26" src="https://github.com/openedx/frontend-app-learner-record/assets/19806032/1500eace-67d2-46a9-893c-bc790c33681c">

<img width="1840" alt="Снимок экрана 2024-04-04 в 01 14 52" src="https://github.com/openedx/frontend-app-learner-record/assets/19806032/7f67b9fd-b536-43c2-8bba-7b0c83e7637a">

2024-04-03 22:28 UTC, openedx-webhooks commented
Thanks for the pull request, @Lunyachek! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-05-20 13:27 UTC, justinhynes commented
Once the change in the main branch is accepted, I'll take a look at and approve this backport PR.

2024-05-20 20:00 UTC, justinhynes requested changes
Blocking backport until the original PR (#318) has gone through AXIM product review.

2024-12-02 17:52 UTC, justinhynes commented
@Lunyachek I'm going to close this PR. At this point it was intended for backport to Quince, but Redwood has come and gone in the time we've spent waiting for product review on the original changes. With Sumac coming... I don't see us backporting this to Quince at this point. Feel free to reopen if you disagree.

2024-12-02 17:52 UTC, closed without merging